// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dfc_grpc.proto

package com.sd.dfc.server;

public interface CepOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.Cep)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 origem = 1;</code>
   */
  int getOrigem();

  /**
   * <code>optional int32 destino = 2;</code>
   */
  int getDestino();
}
