// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dfc_grpc.proto

package com.sd.dfc.server;

public final class DfcProto {
  private DfcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_HelloReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_Cep_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_Cep_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016dfc_grpc.proto\022\006server\"\034\n\014HelloRequest" +
      "\022\014\n\004name\030\001 \001(\t\"\035\n\nHelloReply\022\017\n\007message\030" +
      "\001 \001(\t\"&\n\003Cep\022\016\n\006origem\030\001 \001(\005\022\017\n\007destino\030" +
      "\002 \001(\0052A\n\007Greeter\0226\n\010SayHello\022\024.server.He" +
      "lloRequest\032\022.server.HelloReply\"\000B%\n\021com." +
      "sd.dfc.serverB\010DfcProtoP\001\242\002\003DPRb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_server_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_server_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_server_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_server_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_server_Cep_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_server_Cep_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_Cep_descriptor,
        new java.lang.String[] { "Origem", "Destino", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
