// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dfc_grpc.proto

package com.sd.dfc.server;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
