// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dfc_grpc.proto

package com.sd.dfc.server;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
