// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: business.proto

package com.sd.grpc;

public final class Business {
  private Business() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PrecoRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PrecoRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 cep = 1;</code>
     */
    long getCep();

    /**
     * <code>double peso = 2;</code>
     */
    double getPeso();
  }
  /**
   * Protobuf type {@code PrecoRequest}
   */
  public  static final class PrecoRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PrecoRequest)
      PrecoRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PrecoRequest.newBuilder() to construct.
    private PrecoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PrecoRequest() {
      cep_ = 0L;
      peso_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PrecoRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              cep_ = input.readInt64();
              break;
            }
            case 17: {

              peso_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sd.grpc.Business.internal_static_PrecoRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sd.grpc.Business.internal_static_PrecoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sd.grpc.Business.PrecoRequest.class, com.sd.grpc.Business.PrecoRequest.Builder.class);
    }

    public static final int CEP_FIELD_NUMBER = 1;
    private long cep_;
    /**
     * <code>int64 cep = 1;</code>
     */
    public long getCep() {
      return cep_;
    }

    public static final int PESO_FIELD_NUMBER = 2;
    private double peso_;
    /**
     * <code>double peso = 2;</code>
     */
    public double getPeso() {
      return peso_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cep_ != 0L) {
        output.writeInt64(1, cep_);
      }
      if (peso_ != 0D) {
        output.writeDouble(2, peso_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cep_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, cep_);
      }
      if (peso_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, peso_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sd.grpc.Business.PrecoRequest)) {
        return super.equals(obj);
      }
      com.sd.grpc.Business.PrecoRequest other = (com.sd.grpc.Business.PrecoRequest) obj;

      boolean result = true;
      result = result && (getCep()
          == other.getCep());
      result = result && (
          java.lang.Double.doubleToLongBits(getPeso())
          == java.lang.Double.doubleToLongBits(
              other.getPeso()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CEP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCep());
      hash = (37 * hash) + PESO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPeso()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sd.grpc.Business.PrecoRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sd.grpc.Business.PrecoRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sd.grpc.Business.PrecoRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sd.grpc.Business.PrecoRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sd.grpc.Business.PrecoRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sd.grpc.Business.PrecoRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sd.grpc.Business.PrecoRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sd.grpc.Business.PrecoRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sd.grpc.Business.PrecoRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sd.grpc.Business.PrecoRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sd.grpc.Business.PrecoRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sd.grpc.Business.PrecoRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sd.grpc.Business.PrecoRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PrecoRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PrecoRequest)
        com.sd.grpc.Business.PrecoRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sd.grpc.Business.internal_static_PrecoRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sd.grpc.Business.internal_static_PrecoRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sd.grpc.Business.PrecoRequest.class, com.sd.grpc.Business.PrecoRequest.Builder.class);
      }

      // Construct using com.sd.grpc.Business.PrecoRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cep_ = 0L;

        peso_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sd.grpc.Business.internal_static_PrecoRequest_descriptor;
      }

      @java.lang.Override
      public com.sd.grpc.Business.PrecoRequest getDefaultInstanceForType() {
        return com.sd.grpc.Business.PrecoRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.sd.grpc.Business.PrecoRequest build() {
        com.sd.grpc.Business.PrecoRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sd.grpc.Business.PrecoRequest buildPartial() {
        com.sd.grpc.Business.PrecoRequest result = new com.sd.grpc.Business.PrecoRequest(this);
        result.cep_ = cep_;
        result.peso_ = peso_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sd.grpc.Business.PrecoRequest) {
          return mergeFrom((com.sd.grpc.Business.PrecoRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sd.grpc.Business.PrecoRequest other) {
        if (other == com.sd.grpc.Business.PrecoRequest.getDefaultInstance()) return this;
        if (other.getCep() != 0L) {
          setCep(other.getCep());
        }
        if (other.getPeso() != 0D) {
          setPeso(other.getPeso());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sd.grpc.Business.PrecoRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sd.grpc.Business.PrecoRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long cep_ ;
      /**
       * <code>int64 cep = 1;</code>
       */
      public long getCep() {
        return cep_;
      }
      /**
       * <code>int64 cep = 1;</code>
       */
      public Builder setCep(long value) {
        
        cep_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 cep = 1;</code>
       */
      public Builder clearCep() {
        
        cep_ = 0L;
        onChanged();
        return this;
      }

      private double peso_ ;
      /**
       * <code>double peso = 2;</code>
       */
      public double getPeso() {
        return peso_;
      }
      /**
       * <code>double peso = 2;</code>
       */
      public Builder setPeso(double value) {
        
        peso_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double peso = 2;</code>
       */
      public Builder clearPeso() {
        
        peso_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PrecoRequest)
    }

    // @@protoc_insertion_point(class_scope:PrecoRequest)
    private static final com.sd.grpc.Business.PrecoRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sd.grpc.Business.PrecoRequest();
    }

    public static com.sd.grpc.Business.PrecoRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PrecoRequest>
        PARSER = new com.google.protobuf.AbstractParser<PrecoRequest>() {
      @java.lang.Override
      public PrecoRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PrecoRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PrecoRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PrecoRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sd.grpc.Business.PrecoRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PrecoReturnOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PrecoReturn)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 responseCode = 1;</code>
     */
    int getResponseCode();

    /**
     * <code>string transportadora = 2;</code>
     */
    java.lang.String getTransportadora();
    /**
     * <code>string transportadora = 2;</code>
     */
    com.google.protobuf.ByteString
        getTransportadoraBytes();

    /**
     * <code>double price = 3;</code>
     */
    double getPrice();
  }
  /**
   * Protobuf type {@code PrecoReturn}
   */
  public  static final class PrecoReturn extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PrecoReturn)
      PrecoReturnOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PrecoReturn.newBuilder() to construct.
    private PrecoReturn(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PrecoReturn() {
      responseCode_ = 0;
      transportadora_ = "";
      price_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PrecoReturn(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              responseCode_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              transportadora_ = s;
              break;
            }
            case 25: {

              price_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sd.grpc.Business.internal_static_PrecoReturn_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sd.grpc.Business.internal_static_PrecoReturn_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sd.grpc.Business.PrecoReturn.class, com.sd.grpc.Business.PrecoReturn.Builder.class);
    }

    public static final int RESPONSECODE_FIELD_NUMBER = 1;
    private int responseCode_;
    /**
     * <code>int32 responseCode = 1;</code>
     */
    public int getResponseCode() {
      return responseCode_;
    }

    public static final int TRANSPORTADORA_FIELD_NUMBER = 2;
    private volatile java.lang.Object transportadora_;
    /**
     * <code>string transportadora = 2;</code>
     */
    public java.lang.String getTransportadora() {
      java.lang.Object ref = transportadora_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transportadora_ = s;
        return s;
      }
    }
    /**
     * <code>string transportadora = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTransportadoraBytes() {
      java.lang.Object ref = transportadora_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transportadora_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 3;
    private double price_;
    /**
     * <code>double price = 3;</code>
     */
    public double getPrice() {
      return price_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (responseCode_ != 0) {
        output.writeInt32(1, responseCode_);
      }
      if (!getTransportadoraBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, transportadora_);
      }
      if (price_ != 0D) {
        output.writeDouble(3, price_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (responseCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, responseCode_);
      }
      if (!getTransportadoraBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, transportadora_);
      }
      if (price_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, price_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sd.grpc.Business.PrecoReturn)) {
        return super.equals(obj);
      }
      com.sd.grpc.Business.PrecoReturn other = (com.sd.grpc.Business.PrecoReturn) obj;

      boolean result = true;
      result = result && (getResponseCode()
          == other.getResponseCode());
      result = result && getTransportadora()
          .equals(other.getTransportadora());
      result = result && (
          java.lang.Double.doubleToLongBits(getPrice())
          == java.lang.Double.doubleToLongBits(
              other.getPrice()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSECODE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseCode();
      hash = (37 * hash) + TRANSPORTADORA_FIELD_NUMBER;
      hash = (53 * hash) + getTransportadora().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPrice()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sd.grpc.Business.PrecoReturn parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sd.grpc.Business.PrecoReturn parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sd.grpc.Business.PrecoReturn parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sd.grpc.Business.PrecoReturn parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sd.grpc.Business.PrecoReturn parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sd.grpc.Business.PrecoReturn parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sd.grpc.Business.PrecoReturn parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sd.grpc.Business.PrecoReturn parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sd.grpc.Business.PrecoReturn parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sd.grpc.Business.PrecoReturn parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sd.grpc.Business.PrecoReturn parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sd.grpc.Business.PrecoReturn parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sd.grpc.Business.PrecoReturn prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PrecoReturn}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PrecoReturn)
        com.sd.grpc.Business.PrecoReturnOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sd.grpc.Business.internal_static_PrecoReturn_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sd.grpc.Business.internal_static_PrecoReturn_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sd.grpc.Business.PrecoReturn.class, com.sd.grpc.Business.PrecoReturn.Builder.class);
      }

      // Construct using com.sd.grpc.Business.PrecoReturn.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responseCode_ = 0;

        transportadora_ = "";

        price_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sd.grpc.Business.internal_static_PrecoReturn_descriptor;
      }

      @java.lang.Override
      public com.sd.grpc.Business.PrecoReturn getDefaultInstanceForType() {
        return com.sd.grpc.Business.PrecoReturn.getDefaultInstance();
      }

      @java.lang.Override
      public com.sd.grpc.Business.PrecoReturn build() {
        com.sd.grpc.Business.PrecoReturn result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sd.grpc.Business.PrecoReturn buildPartial() {
        com.sd.grpc.Business.PrecoReturn result = new com.sd.grpc.Business.PrecoReturn(this);
        result.responseCode_ = responseCode_;
        result.transportadora_ = transportadora_;
        result.price_ = price_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sd.grpc.Business.PrecoReturn) {
          return mergeFrom((com.sd.grpc.Business.PrecoReturn)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sd.grpc.Business.PrecoReturn other) {
        if (other == com.sd.grpc.Business.PrecoReturn.getDefaultInstance()) return this;
        if (other.getResponseCode() != 0) {
          setResponseCode(other.getResponseCode());
        }
        if (!other.getTransportadora().isEmpty()) {
          transportadora_ = other.transportadora_;
          onChanged();
        }
        if (other.getPrice() != 0D) {
          setPrice(other.getPrice());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sd.grpc.Business.PrecoReturn parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sd.grpc.Business.PrecoReturn) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int responseCode_ ;
      /**
       * <code>int32 responseCode = 1;</code>
       */
      public int getResponseCode() {
        return responseCode_;
      }
      /**
       * <code>int32 responseCode = 1;</code>
       */
      public Builder setResponseCode(int value) {
        
        responseCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 responseCode = 1;</code>
       */
      public Builder clearResponseCode() {
        
        responseCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object transportadora_ = "";
      /**
       * <code>string transportadora = 2;</code>
       */
      public java.lang.String getTransportadora() {
        java.lang.Object ref = transportadora_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          transportadora_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string transportadora = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTransportadoraBytes() {
        java.lang.Object ref = transportadora_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transportadora_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string transportadora = 2;</code>
       */
      public Builder setTransportadora(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        transportadora_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string transportadora = 2;</code>
       */
      public Builder clearTransportadora() {
        
        transportadora_ = getDefaultInstance().getTransportadora();
        onChanged();
        return this;
      }
      /**
       * <code>string transportadora = 2;</code>
       */
      public Builder setTransportadoraBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        transportadora_ = value;
        onChanged();
        return this;
      }

      private double price_ ;
      /**
       * <code>double price = 3;</code>
       */
      public double getPrice() {
        return price_;
      }
      /**
       * <code>double price = 3;</code>
       */
      public Builder setPrice(double value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double price = 3;</code>
       */
      public Builder clearPrice() {
        
        price_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PrecoReturn)
    }

    // @@protoc_insertion_point(class_scope:PrecoReturn)
    private static final com.sd.grpc.Business.PrecoReturn DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sd.grpc.Business.PrecoReturn();
    }

    public static com.sd.grpc.Business.PrecoReturn getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PrecoReturn>
        PARSER = new com.google.protobuf.AbstractParser<PrecoReturn>() {
      @java.lang.Override
      public PrecoReturn parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PrecoReturn(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PrecoReturn> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PrecoReturn> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sd.grpc.Business.PrecoReturn getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrecoRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrecoRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrecoReturn_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrecoReturn_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016business.proto\")\n\014PrecoRequest\022\013\n\003cep\030" +
      "\001 \001(\003\022\014\n\004peso\030\002 \001(\001\"J\n\013PrecoReturn\022\024\n\014re" +
      "sponseCode\030\001 \001(\005\022\026\n\016transportadora\030\002 \001(\t" +
      "\022\r\n\005price\030\003 \001(\00126\n\007pricing\022+\n\ndefPricing" +
      "\022\r.PrecoRequest\032\014.PrecoReturn0\001B\r\n\013com.s" +
      "d.grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PrecoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PrecoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrecoRequest_descriptor,
        new java.lang.String[] { "Cep", "Peso", });
    internal_static_PrecoReturn_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PrecoReturn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrecoReturn_descriptor,
        new java.lang.String[] { "ResponseCode", "Transportadora", "Price", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
